version: '3.8'

services:
  backend:
    build: .
    container_name: task-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/tasks.db